In [1]:
import numpy
import qubit_matmul

In [14]:
x = numpy.array([0.0]*8)
y = x.copy()
x[0] = 1.0

In [15]:
mat1 = qubit_matmul.TensorMatf64([0], [0.0, 1.0, 1.0, 0.0])
mat2 = qubit_matmul.TensorMatf64([1], [0.0, 1.0, 1.0, 0.0])
mat3 = qubit_matmul.TensorMatf64([2], [0.0, 1.0, 1.0, 0.0])

In [16]:
mat1.apply(x, y)
y

array([0., 0., 0., 0., 1., 0., 0., 0.])

In [17]:
nmat = (mat1 + mat2 + mat3) @ (mat1 + mat2 + mat3)

In [18]:
nmat.apply(x)

array([3., 0., 0., 2., 0., 2., 2., 0.])

In [19]:
mat1.get_dense(1)

array([[0., 1.],
       [1., 0.]])

In [20]:
nmat.get_dense(3)

array([[3., 0., 0., 2., 0., 2., 2., 0.],
       [0., 3., 2., 0., 2., 0., 0., 2.],
       [0., 2., 3., 0., 2., 0., 0., 2.],
       [2., 0., 0., 3., 0., 2., 2., 0.],
       [0., 2., 2., 0., 3., 0., 0., 2.],
       [2., 0., 0., 2., 0., 3., 2., 0.],
       [2., 0., 0., 2., 0., 2., 3., 0.],
       [0., 2., 2., 0., 2., 0., 0., 3.]])

In [21]:
nmat.get_dense(3)[0,:]

array([3., 0., 0., 2., 0., 2., 2., 0.])

In [9]:
nmat.get_sparse(3).todense()

matrix([[3., 0., 0., 2., 0., 2., 2., 0.],
        [0., 3., 2., 0., 2., 0., 0., 2.],
        [0., 2., 3., 0., 2., 0., 0., 2.],
        [2., 0., 0., 3., 0., 2., 2., 0.],
        [0., 2., 2., 0., 3., 0., 0., 2.],
        [2., 0., 0., 2., 0., 3., 2., 0.],
        [2., 0., 0., 2., 0., 2., 3., 0.],
        [0., 2., 2., 0., 2., 0., 0., 3.]])

In [10]:
(mat1.get_dense(3) + mat2.get_dense(3) + mat3.get_dense(3)) @ (mat1.get_dense(3) + mat2.get_dense(3) + mat3.get_dense(3))

array([[3., 0., 0., 2., 0., 2., 2., 0.],
       [0., 3., 2., 0., 2., 0., 0., 2.],
       [0., 2., 3., 0., 2., 0., 0., 2.],
       [2., 0., 0., 3., 0., 2., 2., 0.],
       [0., 2., 2., 0., 3., 0., 0., 2.],
       [2., 0., 0., 2., 0., 3., 2., 0.],
       [2., 0., 0., 2., 0., 2., 3., 0.],
       [0., 2., 2., 0., 2., 0., 0., 3.]])

In [11]:
(mat1 + mat2 + mat3).get_dense(3) @ (mat1 + mat2 + mat3).get_dense(3)

array([[3., 0., 0., 2., 0., 2., 2., 0.],
       [0., 3., 2., 0., 2., 0., 0., 2.],
       [0., 2., 3., 0., 2., 0., 0., 2.],
       [2., 0., 0., 3., 0., 2., 2., 0.],
       [0., 2., 2., 0., 3., 0., 0., 2.],
       [2., 0., 0., 2., 0., 3., 2., 0.],
       [2., 0., 0., 2., 0., 2., 3., 0.],
       [0., 2., 2., 0., 2., 0., 0., 3.]])