In [1]:
import numpy
import qubit_matmul
import scipy.sparse

In [2]:
x = numpy.array([0.0]*16)
y = x.copy()
x[0] = 1.0

In [3]:
mat1 = qubit_matmul.TensorMatf64([0], [0.0, 1.0, 1.0, 0.0])
mat2 = qubit_matmul.TensorMatf64([1], [0.0, 1.0, 1.0, 0.0])
mat3 = qubit_matmul.TensorMatf64([2], [0.0, 1.0, 1.0, 0.0])

In [4]:
mat1.apply(x, y)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
nmat = (mat1 + mat2 + mat3) @ (mat1 + mat2 + mat3)

In [6]:
nmat.apply(x)

array([3., 0., 0., 0., 0., 0., 2., 0., 0., 0., 2., 0., 2., 0., 0., 0.])

In [7]:
mat1.make_sparse(1)

(array([0, 1], dtype=uint64), array([1, 0], dtype=uint64), array([1., 1.]))

In [8]:
rows, cols, vals = mat1.make_sparse(2)
m = scipy.sparse.csc_matrix((vals, (rows, cols)))
m.todense()

matrix([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]])

In [9]:
rows, cols, vals = mat2.make_sparse(2)
m = scipy.sparse.csc_matrix((vals, (rows, cols)))
m.todense()

matrix([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])

In [13]:
rows, cols, vals = nmat.make_sparse(3)
m = scipy.sparse.csc_matrix((vals, (rows, cols)))
m.todense()

matrix([[3., 0., 0., 2., 0., 2., 2., 0.],
        [0., 3., 2., 0., 2., 0., 0., 2.],
        [0., 2., 3., 0., 2., 0., 0., 2.],
        [2., 0., 0., 3., 0., 2., 2., 0.],
        [0., 2., 2., 0., 3., 0., 0., 2.],
        [2., 0., 0., 2., 0., 3., 2., 0.],
        [2., 0., 0., 2., 0., 2., 3., 0.],
        [0., 2., 2., 0., 2., 0., 0., 3.]])