In [1]:
import numpy
import qubit_matmul
from matplotlib import pyplot

# Single Qubit

In [61]:
N = 1
D = 1 << N

v = numpy.array([[1.0, 0.0, 0.0, 1.0]])

mmat = (v.T @ v).flatten()

def lineline(i,n=N):
    return qubit_matmul.TensorMatf64([i,i+1], numpy.eye(1 << (2*n)).flatten()).get_dense(2*n)
def capcap(i,n=N):
    return qubit_matmul.TensorMatf64([i,i+1], mmat).get_dense(2*n)

m = (lineline(0) + capcap(0))/(D+1)

In [62]:
m

array([[0.66666667, 0.        , 0.        , 0.33333333],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.33333333, 0.        ],
       [0.33333333, 0.        , 0.        , 0.66666667]])

In [63]:
im = (D+1)*lineline(0) - capcap(0)
im

array([[ 2.,  0.,  0., -1.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0.,  3.,  0.],
       [-1.,  0.,  0.,  2.]])

In [64]:
m @ im

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Two Qubit Gates with shared Qubit Env

In [121]:
N = 2
D = 1 << N

vv = numpy.kron(v,v)
mmvvmat = (vv.T @ vv).flatten()

def lineline(i,j,n=N):
    return qubit_matmul.TensorMatf64([2*i,2*i+1,2*j,2*j+1], numpy.eye(1 << (2*N)).flatten()).get_dense(2*n)
def capcap(i,j,n=N):
    return qubit_matmul.TensorMatf64([2*i,2*i+1,2*j,2*j+1], mmvvmat).get_dense(2*n)

In [123]:
ma = (lineline(0,1,n=3) + capcap(0,1,n=3))/(D + 1)
mb = (lineline(0,2,n=3) + capcap(0,2,n=3))/(D + 1)

ma @ mb

array([[0.2 , 0.  , 0.  , ..., 0.  , 0.  , 0.08],
       [0.  , 0.08, 0.  , ..., 0.04, 0.  , 0.  ],
       [0.  , 0.  , 0.08, ..., 0.  , 0.04, 0.  ],
       ...,
       [0.  , 0.04, 0.  , ..., 0.08, 0.  , 0.  ],
       [0.  , 0.  , 0.04, ..., 0.  , 0.08, 0.  ],
       [0.08, 0.  , 0.  , ..., 0.  , 0.  , 0.2 ]])

In [124]:
numpy.linalg.inv(ma @ mb)

array([[17.,  0.,  0., ...,  0.,  0.,  2.],
       [ 0., 20.,  0., ..., -5.,  0.,  0.],
       [ 0.,  0., 20., ...,  0., -5.,  0.],
       ...,
       [ 0., -5.,  0., ..., 20.,  0.,  0.],
       [ 0.,  0., -5., ...,  0., 20.,  0.],
       [ 2.,  0.,  0., ...,  0.,  0., 17.]])

In [125]:
((D+1)*lineline(0,1,n=3) - capcap(0,1,n=3)) @ ((D+1)*lineline(0,2,n=3) - capcap(0,2,n=3))

array([[17.,  0.,  0., ...,  0.,  0.,  2.],
       [ 0., 20.,  0., ..., -5.,  0.,  0.],
       [ 0.,  0., 20., ...,  0., -5.,  0.],
       ...,
       [ 0., -5.,  0., ..., 20.,  0.,  0.],
       [ 0.,  0., -5., ...,  0., 20.,  0.],
       [ 2.,  0.,  0., ...,  0.,  0., 17.]])

# Two Qubit Number Conservation

In [126]:
#Single qubit mat
v = numpy.array([[1.,0.,0.,1.]])
mv1 = v.T @ v
mv1

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.]])